version: '3.4'

volumes:
  data:

services:
  server:
    image: node:latest
    ports:
      - '3333:3333'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - mysql
      - phpmyadmin
      - migration

  migration:
    image: node:latest
    command: ["npm", "run", "migrate"]
    depends_on:
      - mysql
    links:
      - mysql

  client:
    image: mysql:5.6
    command: mysql -uroot -hmysql ${DB_DATABASE}
    links:
      - mysql
    depends_on:
      - mysql

  mysql:
    image: mysql:5.6
    ports:
      - '3306:3306'
    volumes:
      - data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - mysql
    ports:
      - 80:80
    environment:
      - PMA_ARBITRARY=1
    links:
      - mysql
